### ISSUE TITLE
Patch.__init__() missing 1 required positional argument: 'key'

### ISSUE THREAD

**Issue by joelburget** [JadenFiotto-Kaufman/nnsight#33]
I can provide more context if useful, but I think this is pretty straightforward: this call to `Patch` is missing the third (`key`) argument.

https://github.com/JadenFiotto-Kaufman/nnsight/blob/cab401e14545e1a24c2671132404ee3a7ac60456/src/nnsight/models/AbstractModel.py#L94-L96

**Comment by JadenFiotto-Kaufman** [comment]
@joelburget Good catch thanks. Fixed on dev.
