### ISSUE TITLE
Add links to source code in documentation

### ISSUE THREAD

**Issue by ericwtodd** [JadenFiotto-Kaufman/nnsight#90]
I think it would be helpful in the documentation to have links to relevant source code.  It would make it easier to check implementation details if someone is trying to deeply understand a part of the nnsight code.

As an example, here's a link to the PyTorch docs that do this: https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module

**Comment by cadentj** [comment]
Added! See documentation.

ex. http://nnsight.net/documentation/envoy/
